-- MySQL Script generated by MySQL Workbench
-- 04/13/16 14:14:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rocnikova
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rocnikova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rocnikova` DEFAULT CHARACTER SET utf8 ;
USE `rocnikova` ;

-- -----------------------------------------------------
-- Table `rocnikova`.`obory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocnikova`.`obory` (
  `Id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(45) NOT NULL,
  `DelkaStudia` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rocnikova`.`studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocnikova`.`studenti` (
  `Id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(20) NOT NULL,
  `Prijmeni` VARCHAR(30) NOT NULL,
  `obory_Id` TINYINT(3) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_studenti_obory_idx` (`obory_Id` ASC),
  CONSTRAINT `fk_studenti_obory`
    FOREIGN KEY (`obory_Id`)
    REFERENCES `rocnikova`.`obory` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
